name: Deploy Workflow new

on:
  pull_request:
    types:
      - closed

jobs:
  initial_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Deployment Steps
        run: |
          echo "Initial deployment steps go here"

  manual_approval:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov pylint flake8 mypy bandit
    
        - name: Run Final Steps
          run: |
            pytest --cov=python--cov-fail-under=60

